name: publish

on:
  push:
    branches: [ master, develop ]

jobs:
  build:

    runs-on: ubuntu-latest
    environment: CommonEnv
    
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET Core SDK 7
      uses: actions/setup-dotnet@v3.2.0
      with:
        dotnet-version: '7.0.x'
    - name: Restore .Net
      run: dotnet restore src
    - name: Configure version
      run: |
        git fetch --unshallow
        lastTag=$(git describe --tags --abbrev=0)
        lastTagMainVersion=$(sed -n 's/^\([0-9]*\.[0-9]*\).*/\1/p' <<<"$lastTag")
        echo Last tag version is $lastTagMainVersion
        currentVersion=$(cat VERSION)
        echo Current version is $currentVersion
        currentMainVersion=$(sed -n 's/^\([0-9]*\.[0-9]*\).*/\1/p' <VERSION)
        echo Current main version is $currentMainVersion
        if [ "$lastTagMainVersion" = "$currentMainVersion" ]
        then
          echo "Version the same."
          lastTagBuildVersion=$(sed -n 's/^[0-9]*\.[0-9]*\.\([0-9]*\).*/\1/p' <<<"$lastTag")
          newBuildVersion=$((lastTagBuildVersion+1))
          newVersion="$lastTagMainVersion"."$newBuildVersion"
          echo "newVersion=$newVersion"
          echo "newVersion=$newVersion" >> $GITHUB_ENV
        else
          echo "New version!"
          newVersion="$currentMainVersion".1
          VersionPrefix=$newVersion
          echo "newVersion=$newVersion"
          echo "newVersion=$newVersion" >> $GITHUB_ENV
        fi
        sed -i -e "s/\(<Version>\)\(.*\)\(<\/Version>\)/\1${{env.newVersion}}\3/" src/AsyncReactAwait/AsyncReactAwait.csproj
    - name: Test
      run: dotnet test src --verbosity normal
    - name: Build
      run: dotnet build src/AsyncReactAwait/AsyncReactAwait.csproj --no-dependencies --output src/build
    - name: Publish package to GitHub
      if: github.ref == 'refs/heads/master'
      run: |
       dotnet nuget add source --username kekchpek --password ${{ secrets.PAT_TOKEN }} --store-password-in-clear-text --name github "https://nuget.pkg.github.com/kekchpek/index.json"
       dotnet nuget push build/*.nupkg --api-key ${{secrets.PAT_TOKEN}} --source github
    - name: Publish package to Nuget
      if: github.ref == 'refs/heads/master'
      run: |
       dotnet nuget push build/*.nupkg --api-key ${{secrets.NUGET_API_KEY}} --source https://api.nuget.org/v3/index.json
    - name: Zip build
      run: zip AsyncReactAwait.zip src/build/AsyncReactAwait.dll src/build/AsyncReactAwait.xml
    - name: Tag non-release
      if: github.ref != 'refs/heads/master'
      run: |
        git tag ${{ env.newVersion }}
        git push --tags
    - name: Create Release
      uses: ncipollo/release-action@v1.13.0
      with:
        tag: ${{ env.newVersion }}
        name: Release ${{ env.newVersion }}
        artifacts: "src/build/*.nupkg, AsyncReactAwait.zip"
        token: ${{ secrets.GITHUB_TOKEN }}
    - name: Expose as artifact
      uses: actions/upload-artifact@v3.1.3
      with:
       name: Build
       path: src/AsyncReactAwait/build
